version: '3.8'
services:
  web:
    # Replace <your-github-username> with your actual username in lowercase
    image: ${IMAGE_URI}
    ports:
      - "80:5000"
    restart: always
    environment:
      - FLASK_AS_MAIN=true
