version: '3.8'
services:
  web:
    # Replace <your-github-username> with your actual username in lowercase
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER_LOWERCASE}/bluelisandro.github.io:latest
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_AS_MAIN=true
